use_frameworks!

target 'TomorrowIbanScanner_Example' do
  pod 'TomorrowIbanScanner', :path => '../'

  target 'TomorrowIbanScanner_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
