platform :ios, '11.0'
use_frameworks!

target 'TomorrowIbanScanner_Example' do
  pod 'SwiftLint'

  target 'TomorrowIbanScanner_ExampleTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
